# -*- coding: utf-8 -*-
"""OralNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vk65it-2CmPqDe-SMuT_iC_DboHfKsHl
"""

! pip install tensorflow

from google.colab import drive
drive.mount('/content/drive')



import os
import shutil
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from PIL import Image

# 1. Parameters
BATCH_SIZE = 32
IMAGE_SIZE = 200
EPOCHS = 10
CHANNELS = 3

original_data_path = "/content/drive/My Drive/oral1/OralCancer1"
augmented_data_path = "/content/augmented_oral_cancer_dataset"

# 2. Augmentation
if os.path.exists(augmented_data_path):
    shutil.rmtree(augmented_data_path)
os.makedirs(augmented_data_path, exist_ok=True)

datagen = ImageDataGenerator(
    rotation_range=30,
    zoom_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    rescale=1./255
)

target_count_per_class = 500

for class_label in os.listdir(original_data_path):
    class_dir = os.path.join(original_data_path, class_label)
    save_dir = os.path.join(augmented_data_path, class_label)
    os.makedirs(save_dir, exist_ok=True)

    images = [f for f in os.listdir(class_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
    total_generated = 0

    for image_name in images:
        image_path = os.path.join(class_dir, image_name)
        img = Image.open(image_path).convert('RGB').resize((IMAGE_SIZE, IMAGE_SIZE))
        x = tf.keras.utils.img_to_array(img)
        x = x.reshape((1,) + x.shape)
        img.save(os.path.join(save_dir, f"original_{image_name}"))
        total_generated += 1

        for batch in datagen.flow(x, batch_size=1, save_to_dir=save_dir, save_prefix='aug', save_format='jpeg'):
            total_generated += 1
            if total_generated >= target_count_per_class:
                break
        if total_generated >= target_count_per_class:
            break

print("✅ Augmentation complete.")

# 3. Load Dataset
dataset = tf.keras.utils.image_dataset_from_directory(
    augmented_data_path,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)
class_names = dataset.class_names
print("Class Names:", class_names)

# 4. Train-Test Split
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)
    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# 5. LGA Block (Corrected)
class LGABlock(tf.keras.layers.Layer):
    def __init__(self, dim, name="LGA", **kwargs):
        super(LGABlock, self).__init__(name=name, **kwargs)
        self.dim = dim
        self.conv_proj = layers.Conv2D(dim, (1, 1), padding='same')
        self.bn = layers.BatchNormalization()
        self.relu = layers.ReLU()

    def call(self, inputs):
        z = self.conv_proj(inputs)  # [B, H, W, C]
        B = tf.shape(z)[0]
        H = tf.shape(z)[1]
        W = tf.shape(z)[2]
        C = tf.shape(z)[3]
        N = H * W

        z_flat = tf.reshape(z, [B, N, C])  # [B, N, C]

        zi = tf.expand_dims(z_flat, axis=2)  # [B, N, 1, C]
        zj = tf.expand_dims(z_flat, axis=1)  # [B, 1, N, C]
        dist = tf.norm(zi - zj, axis=-1)     # [B, N, N]

        affinity = tf.nn.softmax(-dist, axis=-1)  # [B, N, N]
        recon = tf.matmul(affinity, z_flat)       # [B, N, C]

        recon = tf.reshape(recon, [B, H, W, C])
        out = self.bn(recon + z)
        return self.relu(out)

# 6. AMSA Transformer Encoder
def AMSA_Transformer(x, num_heads=4, d_model=256):
    norm1 = layers.LayerNormalization()(x)
    attn = layers.MultiHeadAttention(num_heads=num_heads, key_dim=d_model // num_heads)(norm1, norm1)
    x = layers.Add()([x, attn])
    norm2 = layers.LayerNormalization()(x)
    mlp = models.Sequential([
        layers.Dense(d_model * 4, activation='gelu'),
        layers.Dense(d_model)
    ])
    x = layers.Add()([x, mlp(norm2)])
    return x

# 7. Create LWENet Model
def create_LWENet(input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS), n_classes=len(class_names)):
    inputs = layers.Input(shape=input_shape)
    x = layers.Rescaling(1./255)(inputs)
    x = layers.Conv2D(32, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)

    x = layers.Conv2D(64, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)

    x = layers.Conv2D(128, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)

    x = LGABlock(dim=128)(x)

    x = layers.Conv2D(256, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)

    x = AMSA_Transformer(x)

    x = layers.GlobalAveragePooling2D()(x)
    outputs = layers.Dense(n_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model

# 8. Compile & Train
model = create_LWENet()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
)

# 9. Evaluate
test_loss, test_acc = model.evaluate(test_ds)
print(f"✅ Test Accuracy: {test_acc:.4f}")