# -*- coding: utf-8 -*-
"""oral_final_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JeKxYK1-hyl9gualStTp0S5sEUScFtsB
"""

! pip install tensorflow

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
drive.mount('/content/drive')



import os

# Define path to OralCancer dataset
dataset_path = "/content/drive/My Drive/oral1//OralCancer1"

# Verify the dataset is accessible
print("Contents of OralCancer directory:", os.listdir(dataset_path))

import os
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt

# Define path to OralCancer dataset
dataset_path = "/content/drive/My Drive/oral1/OralCancer1"

# Verify the dataset is accessible
print("Contents of OralCancer directory:", os.listdir(dataset_path))

# Set constants
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3

# Load dataset using image_dataset_from_directory
dataset = tf.keras.utils.image_dataset_from_directory(
    dataset_path,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

# Get class names
class_names = dataset.class_names
print("Class Names:", class_names)

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# ✅ Reconfigured CNN Model Based on Image (Model b)
def create_oral_cancer_model(input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS), n_classes=len(class_names)):
    inputs = layers.Input(shape=input_shape)

    # Augmentation Layer (shown in image)
    x = layers.RandomFlip("horizontal")(inputs)
    x = layers.RandomRotation(0.25)(x)
    x = layers.RandomZoom(0.25)(x)
    x = layers.RandomContrast(0.25)(x)
    x = layers.Rescaling(1./255)(x)

    # Block 1
    x = layers.Conv2D(32, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    # Block 2
    x = layers.Conv2D(64, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    # Block 3
    x = layers.Conv2D(128, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    # Block 7-N (more depth)
    x = layers.Conv2D(256, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Flatten()(x)

    # Dense + Dropout layers for fine-tuning
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    # Final Softmax classifier
    outputs = layers.Dense(n_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model

# Create and compile the model
model = create_oral_cancer_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Show model summary
model.summary()

# Train the model with test set as validation data
history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
)

# Evaluate on test data
test_loss, test_acc = model.evaluate(test_ds)
print(f"Test accuracy: {test_acc}")

for images, labels in dataset.take(1):  # just one batch
    for i in range(len(images)):        # or a subset if you'd like
        plt.figure()
        plt.imshow(images[i].numpy().astype("uint8"))
        label_idx = labels[i].numpy()
        plt.title(f"Label: {label_idx} ({class_names[label_idx]})")
        plt.axis("off")
        plt.show()

##############################
# 2) TRAIN/VAL SPLIT
##############################
def get_train_val_split(ds, train_split=0.8, val_split=0.2, shuffle=True, shuffle_size=10000):
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=123)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size)
    return train_ds, val_ds

train_ds, val_ds = get_train_val_split(dataset)
print("Train Batches:", len(train_ds))
print("Validation Batches:", len(val_ds))

train_ds = train_ds.prefetch(tf.data.AUTOTUNE)
val_ds   = val_ds.prefetch(tf.data.AUTOTUNE)

##############################
# 3) ViT BLOCK (patch_size=2)
##############################
class ViTBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, patch_size=4, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.ff_dim = ff_dim
        self.patch_size = patch_size

        self.patch_embed = layers.Conv2D(
            self.embed_dim,
            kernel_size=self.patch_size,
            strides=self.patch_size,
            padding='same'
        )
        self.layernorm1 = layers.LayerNormalization(epsilon=1e-6)
        self.mha = layers.MultiHeadAttention(num_heads=self.num_heads, key_dim=self.embed_dim)
        self.layernorm2 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn = tf.keras.Sequential([
            layers.Dense(self.ff_dim, activation='relu'),
            layers.Dense(self.embed_dim),
        ])

    def call(self, x):
        # x shape: [B, H, W, C]
        x = self.patch_embed(x)  # e.g. if patch_size=2, H->H/2, W->W/2
        B, Hp, Wp, C = tf.shape(x)[0], tf.shape(x)[1], tf.shape(x)[2], tf.shape(x)[3]

        x = tf.reshape(x, (B, Hp * Wp, C))  # Flatten patches
        x = self.layernorm1(x)

        attn_output = self.mha(x, x)  # Self-Attention
        x = x + attn_output           # Skip connection

        x = self.layernorm2(x)
        ffn_output = self.ffn(x)
        x = x + ffn_output            # Skip connection

        # Reshape back to 2D
        x = tf.reshape(x, (B, Hp, Wp, C))
        return x

##############################
# 4) CNN + ViT U-NET MODEL
##############################
def create_cnn_vit_unet(
    input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS),
    num_classes=5,
    vit_embed_dim=128,
    vit_num_heads=4,
    vit_ff_dim=256,
    vit_patch_size=2   # <-- changed default to 2
):
    inputs = layers.Input(shape=input_shape)

    # ENCODER
    x = layers.Conv2D(32, 3, activation='relu', padding='same')(inputs)
    x = layers.MaxPooling2D(2)(x)
    skip1 = x  # shape ~ [128, 128, 32]

    x = layers.Conv2D(64, 3, activation='relu', padding='same')(x)
    x = layers.MaxPooling2D(2)(x)
    skip2 = x  # shape ~ [64, 64, 64]

    x = layers.Conv2D(128, 3, activation='relu', padding='same')(x)
    x = layers.MaxPooling2D(2)(x)
    skip3 = x  # shape ~ [32, 32, 128]

    x = layers.Conv2D(256, 3, activation='relu', padding='same')(x)
    x = layers.MaxPooling2D(2)(x)
    skip4 = x  # shape ~ [16, 16, 256]

    # Bottleneck
    x = layers.Conv2D(512, 3, activation='relu', padding='same')(skip4)

    # ViT BLOCK (with patch_size=2 to avoid shape mismatch)
    x = ViTBlock(
        embed_dim=vit_embed_dim,
        num_heads=vit_num_heads,
        ff_dim=vit_ff_dim,
        patch_size=vit_patch_size
    )(x)

    # Optionally align channels again
    x = layers.Conv2D(512, 1, activation='relu', padding='same')(x)

    # DECODER
    # Up 1:  (16 -> 32)  then concat skip4 (16,16)? No - now x is 8,8 if patch_size=4,
    # but with patch_size=2, shape is (8,8). So let's see:
    # Actually with patch_size=2: 16->8 inside ViT, then we do a TransposeConv(2) => 8->16
    # That matches skip4 (16,16).

    x = layers.Conv2DTranspose(256, 2, strides=2, activation='relu', padding='same')(x)
    # now 8->16
    x = layers.Concatenate()([x, skip4])  # skip4 is (16,16,256)
    x = layers.Conv2D(256, 3, activation='relu', padding='same')(x)

    # Up 2:  (16 -> 32)
    x = layers.Conv2DTranspose(128, 2, strides=2, activation='relu', padding='same')(x)
    x = layers.Concatenate()([x, skip3])  # skip3 is (32,32,128)
    x = layers.Conv2D(128, 3, activation='relu', padding='same')(x)

    # Up 3:  (32 -> 64)
    x = layers.Conv2DTranspose(64, 2, strides=2, activation='relu', padding='same')(x)
    x = layers.Concatenate()([x, skip2])  # skip2 is (64,64,64)
    x = layers.Conv2D(64, 3, activation='relu', padding='same')(x)

    # Up 4:  (64 -> 128)
    x = layers.Conv2DTranspose(32, 2, strides=2, activation='relu', padding='same')(x)
    x = layers.Concatenate()([x, skip1])  # skip1 is (128,128,32)
    x = layers.Conv2D(32, 3, activation='relu', padding='same')(x)

    # OUTPUTS
    distance_map = layers.Conv2D(1, kernel_size=1, activation='sigmoid', name="distance_map")(x)
    seg_map = layers.Conv2D(num_classes, kernel_size=1, activation='softmax', name="cell_map")(x)

    model = models.Model(inputs=inputs, outputs=[distance_map, seg_map])
    return model

##############################
# 5) INSTANTIATE & COMPILE
##############################
num_seg_classes = 5
model = create_cnn_vit_unet(
    input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS),
    num_classes=num_seg_classes,
    vit_patch_size=2   # <-- CRUCIAL to fix shape mismatch
)

# Example multi-output loss/metrics
model.compile(
    optimizer='adam',
    loss={
        "distance_map": tf.keras.losses.BinaryCrossentropy(),
        "cell_map": tf.keras.losses.CategoricalCrossentropy()
    },
    metrics={
        "distance_map": ["accuracy"],
        "cell_map": ["accuracy"],
    }
)

model.summary()

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

# Define a function to split the dataset into training, validation, and testing
def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)
    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(val_size)
    test_ds = ds.skip(train_size).skip(val_size)
    # Autotune all the 3 datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    val_ds = val_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    return train_ds, val_ds, test_ds

train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset)

# Define data preprocessing and augmentation pipelines
resize_and_rescale = tf.keras.Sequential([
    layers.experimental.preprocessing.Resizing(IMAGE_SIZE, IMAGE_SIZE),
    layers.experimental.preprocessing.Rescaling(1./255),
])

input_shape = (BATCH_SIZE, IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 9

# Create the CNN model
model = models.Sequential([
    resize_and_rescale,
    layers.Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])
model.build(input_shape=input_shape)

# Compile the model
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

model.summary()

def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + val_split + test_split) == 1

    # Calculate the dataset size
    ds_size = sum(1 for _ in ds)

    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)

    # Split dataset
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)

    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(val_size)
    test_ds = ds.skip(train_size).skip(val_size)

    # Optimize each dataset partition with cache and prefetch
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    val_ds = val_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, val_ds, test_ds

# Train the model
history = model.fit(
    train_ds,
    batch_size=BATCH_SIZE,
    validation_data=test_ds,
    verbose=1,
    epochs=EPOCHS,
)

print(f"Training dataset size: {len(train_ds)}")
print(f"Validation dataset size: {len(val_ds)}")
print(f"Testing dataset size: {len(test_ds)}")

# Evaluate the model on the test dataset
model.evaluate(test_ds)

# Plot training history
acc = history.history['accuracy']
loss = history.history['loss']

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(range(EPOCHS), acc, label=' Accuracy')
plt.legend(loc='lower right')
plt.title('Accuracy')
plt.subplot(1, 2, 2)
plt.plot(range(EPOCHS), loss, label=' Loss')
plt.legend(loc='upper right')
plt.title('Loss')
plt.show()

# Example of using the trained model for prediction
image_path = r"C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer\non-cancer\20200314_1130302.jpg"  # Replace with the actual path to your local image
image = tf.keras.preprocessing.image.load_img(image_path, target_size=(256, 256))
image_array = tf.keras.preprocessing.image.img_to_array(image)
scaled_img = np.expand_dims(image_array, axis=0)

# Predict
pred = model.predict(scaled_img)

# Get the class name with the highest probability
output = class_names[np.argmax(pred)]

# Display the image
plt.figure(figsize=(6, 6))
plt.imshow(image)
plt.title(f'Predicted Class: {output}')
plt.show()

print(f"The predicted class is: {output}")

# Save the trained model
model.save("Oral_cancer_detection.h5")

# Extract training and validation metrics
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

# Plot training and validation accuracy
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(range(EPOCHS), acc, label='Training Accuracy')
plt.plot(range(EPOCHS), val_acc, label='Validation Accuracy', linestyle="--")
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

# Plot training and validation loss
plt.subplot(1, 2, 2)
plt.plot(range(EPOCHS), loss, label='Training Loss')
plt.plot(range(EPOCHS), val_loss, label='Validation Loss', linestyle="--")
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
import numpy as np

# You may want to adjust these parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Get dataset length
len(dataset)

# Display a batch of images and their labels
for image_batch, label_batch in dataset.take(1):
    print(image_batch.shape)
    print(label_batch.numpy())

# Define a function to split the dataset into training, validation, and testing
def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.2, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)
    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(val_size)
    test_ds = ds.skip(train_size).skip(val_size)
    # Autotune all the 3 datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    val_ds = val_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    return train_ds, val_ds, test_ds

train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset)

# Define data preprocessing and augmentation pipelines
resize_and_rescale = tf.keras.Sequential([
    layers.experimental.preprocessing.Resizing(IMAGE_SIZE, IMAGE_SIZE),
    layers.experimental.preprocessing.Rescaling(1./255),
])

input_shape = (BATCH_SIZE, IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 9

# Create the CNN model
model = models.Sequential([
    resize_and_rescale,
    layers.Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])
model.build(input_shape=input_shape)

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
from tensorflow.keras.applications import ResNet50, InceptionV3
import numpy as np

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3
INPUT_SHAPE = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
N_CLASSES = 9

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
    r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

# Function to split dataset into training, validation, and testing
def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)
    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(int(val_split * ds_size))
    test_ds = ds.skip(train_size).skip(int(val_split * ds_size))
    return train_ds.prefetch(tf.data.AUTOTUNE), val_ds.prefetch(tf.data.AUTOTUNE), test_ds.prefetch(tf.data.AUTOTUNE)

train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset)

# Pre-trained ResNet50 model for feature extraction
resnet_model = ResNet50(include_top=False, weights='imagenet', input_shape=INPUT_SHAPE)
resnet_model.trainable = False  # Freeze the ResNet layers

# Pre-trained InceptionV3 model for feature extraction
inception_model = InceptionV3(include_top=False, weights='imagenet', input_shape=INPUT_SHAPE)
inception_model.trainable = False  # Freeze the Inception layers

# Define the hybrid model that combines ResNet50 and InceptionV3
input_layer = layers.Input(shape=INPUT_SHAPE)

# Pass inputs through ResNet50
resnet_features = resnet_model(input_layer)
resnet_features = layers.GlobalAveragePooling2D()(resnet_features)

# Pass inputs through InceptionV3
inception_features = inception_model(input_layer)
inception_features = layers.GlobalAveragePooling2D()(inception_features)

# Concatenate the features from both models
combined_features = layers.Concatenate()([resnet_features, inception_features])

# Add final dense layers for classification
x = layers.Dense(128, activation='relu')(combined_features)
x = layers.Dropout(0.3)(x)
output_layer = layers.Dense(N_CLASSES, activation='softmax')(x)

# Compile the hybrid model
hybrid_model = models.Model(inputs=input_layer, outputs=output_layer)
hybrid_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Display the model summary
hybrid_model.summary()

# Train the model
history = hybrid_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS
)

# Extract training and validation metrics
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

# Plot training and validation accuracy
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(range(EPOCHS), acc, label='Training Accuracy')
plt.plot(range(EPOCHS), val_acc, label='Validation Accuracy', linestyle="--")
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

# Plot training and validation loss
plt.subplot(1, 2, 2)
plt.plot(range(EPOCHS), loss, label='Training Loss')
plt.plot(range(EPOCHS), val_loss, label='Validation Loss', linestyle="--")
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

# Additional Imports for Evaluation
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Evaluate the model on the test dataset
test_loss, test_accuracy = hybrid_model.evaluate(test_ds)
print(f'Test Accuracy: {test_accuracy:.2f}')

# Get the true labels and predictions for the test set
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred_probs = hybrid_model.predict(test_ds)
y_pred = np.argmax(y_pred_probs, axis=1)

# Confusion Matrix
conf_matrix = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=dataset.class_names, yticklabels=dataset.class_names)
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix')
plt.show()

# Classification Report
class_report = classification_report(y_true, y_pred, target_names=dataset.class_names)
print("Classification Report:\n", class_report)

# ROC Curve and AUC
plt.figure(figsize=(10, 8))
for i in range(N_CLASSES):
    fpr, tpr, _ = roc_curve(y_true == i, y_pred_probs[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {dataset.class_names[i]} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for random guessing
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
from tensorflow.keras.applications import ResNet50, InceptionV3
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3
INPUT_SHAPE = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
N_CLASSES = 9

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
    r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

# Function to split dataset into training, validation, and testing
def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)
    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(int(val_split * ds_size))
    test_ds = ds.skip(train_size).skip(int(val_split * ds_size))
    return train_ds.prefetch(tf.data.AUTOTUNE), val_ds.prefetch(tf.data.AUTOTUNE), test_ds.prefetch(tf.data.AUTOTUNE)

train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset)

# Pre-trained ResNet50 model for feature extraction
resnet_model = ResNet50(include_top=False, weights='imagenet', input_shape=INPUT_SHAPE)
resnet_model.trainable = False  # Freeze the ResNet layers

# Pre-trained InceptionV3 model for feature extraction
inception_model = InceptionV3(include_top=False, weights='imagenet', input_shape=INPUT_SHAPE)
inception_model.trainable = False  # Freeze the Inception layers

# Define the hybrid model that combines ResNet50 and InceptionV3
input_layer = layers.Input(shape=INPUT_SHAPE)

# Pass inputs through ResNet50
resnet_features = resnet_model(input_layer)
resnet_features = layers.GlobalAveragePooling2D()(resnet_features)

# Pass inputs through InceptionV3
inception_features = inception_model(input_layer)
inception_features = layers.GlobalAveragePooling2D()(inception_features)

# Concatenate the features from both models
combined_features = layers.Concatenate()([resnet_features, inception_features])

# Add final dense layers for classification
x = layers.Dense(128, activation='relu')(combined_features)
x = layers.Dropout(0.3)(x)
output_layer = layers.Dense(N_CLASSES, activation='softmax')(x)

# Compile the hybrid model
hybrid_model = models.Model(inputs=input_layer, outputs=output_layer)
hybrid_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Display the model summary
hybrid_model.summary()

# Define EarlyStopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)

# Train the model with early stopping
history = hybrid_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
    callbacks=[early_stopping]
)

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
from tensorflow.keras.applications import ResNet50, InceptionV3
import numpy as np

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3
INPUT_SHAPE = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
N_CLASSES = 9

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
    r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

# Function to split dataset into training, validation, and testing
def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)
    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(int(val_split * ds_size))
    test_ds = ds.skip(train_size).skip(int(val_split * ds_size))
    return train_ds.prefetch(tf.data.AUTOTUNE), val_ds.prefetch(tf.data.AUTOTUNE), test_ds.prefetch(tf.data.AUTOTUNE)

train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset)

# Pre-trained ResNet50 model for feature extraction
resnet_model = ResNet50(include_top=False, weights='imagenet', input_shape=INPUT_SHAPE)
resnet_model.trainable = False  # Freeze the ResNet layers

# Pre-trained InceptionV3 model for feature extraction
inception_model = InceptionV3(include_top=False, weights='imagenet', input_shape=INPUT_SHAPE)
inception_model.trainable = False  # Freeze the Inception layers

# Define the hybrid model that combines ResNet50 and InceptionV3
input_layer = layers.Input(shape=INPUT_SHAPE)

# Pass inputs through ResNet50
resnet_features = resnet_model(input_layer)
resnet_features = layers.GlobalAveragePooling2D()(resnet_features)

# Pass inputs through InceptionV3
inception_features = inception_model(input_layer)
inception_features = layers.GlobalAveragePooling2D()(inception_features)

# Concatenate the features from both models
combined_features = layers.Concatenate()([resnet_features, inception_features])

# Add final dense layers for classification
x = layers.Dense(128, activation='relu')(combined_features)
x = layers.Dropout(0.3)(x)
output_layer = layers.Dense(N_CLASSES, activation='softmax')(x)

# Compile the hybrid model
hybrid_model = models.Model(inputs=input_layer, outputs=output_layer)
hybrid_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Display the model summary
hybrid_model.summary()
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)

# Train the model
history = hybrid_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
        callbacks=[early_stopping]

)

import matplotlib.pyplot as plt

# Extract training and validation metrics
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs_range = range(len(acc))  # Adjust the range to match the number of epochs trained

# Plot training and validation accuracy
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy', linestyle="--")
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

# Plot training and validation loss
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss', linestyle="--")
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

import matplotlib.pyplot as plt

# Extract training and validation metrics
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs_range = range(len(acc))

# Plot training and validation accuracy
plt.figure(figsize=(14, 5))

# Accuracy plot
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy', linewidth=2)
plt.plot(epochs_range, val_acc, label='Validation Accuracy', linestyle="--", linewidth=2)
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.title('Training and Validation Accuracy', fontsize=14)
plt.legend(loc='lower right')
plt.grid(visible=True, linestyle="--", alpha=0.7)

# Loss plot
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss', linewidth=2)
plt.plot(epochs_range, val_loss, label='Validation Loss', linestyle="--", linewidth=2)
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Loss', fontsize=12)
plt.title('Training and Validation Loss', fontsize=14)
plt.legend(loc='upper right')
plt.grid(visible=True, linestyle="--", alpha=0.7)

plt.tight_layout()
plt.show()

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.initializers import HeNormal
import numpy as np

# Parameters
INPUT_SHAPE = (224, 224, 3)
N_CLASSES = 2  # Cancerous and Non-Cancerous

# Custom Hybrid Model Definition
def build_hybrid_model(input_shape=INPUT_SHAPE, n_classes=N_CLASSES):
    input_layer = layers.Input(shape=input_shape)

    # First feature extraction block
    x = layers.Conv2D(64, (3, 3), activation='relu', padding='same', kernel_initializer=HeNormal())(input_layer)
    x = layers.BatchNormalization()(x)
    x = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Second feature extraction block
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Third feature extraction block with Dilation
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same', dilation_rate=2)(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Attention Mechanism
    attention = layers.Conv2D(256, (1, 1), activation='sigmoid')(x)  # Adjust channels to match
    x = layers.Multiply()([x, attention])

    # Flatten the output and add dense layers
    x = layers.Flatten()(x)
    x = layers.Dense(512, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    output_layer = layers.Dense(n_classes, activation='softmax')(x)

    # Compile model
    model = models.Model(inputs=input_layer, outputs=output_layer)
    return model

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt

# Callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)
checkpoint = ModelCheckpoint('novel_hybrid_model.h5', monitor='val_accuracy', save_best_only=True, verbose=1)

# Training
history = hybrid_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=50,
    callbacks=[early_stopping, checkpoint]
)

# Evaluate and Visualize
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', linestyle="--")
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss', linestyle="--")
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
from tensorflow.keras.applications import ResNet50, InceptionV3
import numpy as np

# Parameters
BATCH_SIZE = 32
IMAGE_SIZE = 256
EPOCHS = 30
CHANNELS = 3
INPUT_SHAPE = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
N_CLASSES = 9

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
    r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

# Function to split dataset into training, validation, and testing
def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)
    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(int(val_split * ds_size))
    test_ds = ds.skip(train_size).skip(int(val_split * ds_size))
    return train_ds.prefetch(tf.data.AUTOTUNE), val_ds.prefetch(tf.data.AUTOTUNE), test_ds.prefetch(tf.data.AUTOTUNE)

train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset)

# Pre-trained ResNet50 model for feature extraction
resnet_model = ResNet50(include_top=False, weights='imagenet', input_shape=INPUT_SHAPE)
resnet_model.trainable = False  # Freeze the ResNet layers

# Pre-trained InceptionV3 model for feature extraction
inception_model = InceptionV3(include_top=False, weights='imagenet', input_shape=INPUT_SHAPE)
inception_model.trainable = False  # Freeze the Inception layers

# Define the hybrid model that combines ResNet50 and InceptionV3
input_layer = layers.Input(shape=INPUT_SHAPE)

# Pass inputs through ResNet50
resnet_features = resnet_model(input_layer)
resnet_features = layers.GlobalAveragePooling2D()(resnet_features)

# Pass inputs through InceptionV3
inception_features = inception_model(input_layer)
inception_features = layers.GlobalAveragePooling2D()(inception_features)

# Concatenate the features from both models
combined_features = layers.Concatenate()([resnet_features, inception_features])

# Add final dense layers for classification
x = layers.Dense(128, activation='relu')(combined_features)
x = layers.Dropout(0.3)(x)
output_layer = layers.Dense(N_CLASSES, activation='softmax')(x)

# Compile the hybrid model
hybrid_model = models.Model(inputs=input_layer, outputs=output_layer)
hybrid_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Display the model summary
hybrid_model.summary()
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)

# Train the model
history = hybrid_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
        callbacks=[early_stopping]

)

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt

# You may want to adjust these parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Define a function to split the dataset into training, validation, and testing
def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)
    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(val_size)
    test_ds = ds.skip(train_size).skip(val_size)

    # Autotune all the 3 datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    val_ds = val_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, val_ds, test_ds

train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset)

# Define data preprocessing and augmentation pipelines
resize_and_rescale = tf.keras.Sequential([
    layers.experimental.preprocessing.Resizing(IMAGE_SIZE, IMAGE_SIZE),
    layers.experimental.preprocessing.Rescaling(1./255),
])

# Model inspired by CST-YOLO, customized for classification
def create_oral_cancer_model(input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS), n_classes=len(class_names)):
    inputs = layers.Input(shape=input_shape)

    # Data preprocessing
    x = resize_and_rescale(inputs)

    # Backbone: Initial Convolutional Layers
    x = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Multi-scale feature extraction
    # Path 1
    p1 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    p1 = layers.MaxPooling2D((2, 2))(p1)

    # Path 2 with a larger kernel
    p2 = layers.Conv2D(64, (5, 5), activation='relu', padding='same')(x)
    p2 = layers.MaxPooling2D((2, 2))(p2)

    # Path 3 with a smaller kernel
    p3 = layers.Conv2D(64, (7, 7), activation='relu', padding='same')(x)
    p3 = layers.MaxPooling2D((2, 2))(p3)

    # Concatenate multi-scale features
    x = layers.Concatenate()([p1, p2, p3])

    # Convolutional layers after multi-scale feature fusion
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Additional feature extraction layers
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Flatten and fully connected layers for classification
    x = layers.Flatten()(x)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    # Output layer with softmax for multi-class classification
    outputs = layers.Dense(n_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model

# Create and compile the model
model = create_oral_cancer_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Model summary
model.summary()

# Train the model
history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
)

# Evaluate on test data
test_loss, test_acc = model.evaluate(test_ds)
print(f"Test accuracy: {test_acc}")

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
import numpy as np
import itertools

# You may want to adjust these parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Define a function to split the dataset into training, validation, and testing
def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)
    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(val_size)
    test_ds = ds.skip(train_size).skip(val_size)

    # Autotune all the 3 datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    val_ds = val_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, val_ds, test_ds

train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset)

# Define data preprocessing and augmentation pipelines
resize_and_rescale = tf.keras.Sequential([
    layers.experimental.preprocessing.Resizing(IMAGE_SIZE, IMAGE_SIZE),
    layers.experimental.preprocessing.Rescaling(1./255),
])

# Model inspired by CST-YOLO, customized for classification
def create_oral_cancer_model(input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS), n_classes=len(class_names)):
    inputs = layers.Input(shape=input_shape)

    # Data preprocessing
    x = resize_and_rescale(inputs)

    # Backbone: Initial Convolutional Layers
    x = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Multi-scale feature extraction
    # Path 1
    p1 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    p1 = layers.MaxPooling2D((2, 2))(p1)

    # Path 2 with a larger kernel
    p2 = layers.Conv2D(64, (5, 5), activation='relu', padding='same')(x)
    p2 = layers.MaxPooling2D((2, 2))(p2)

    # Path 3 with a smaller kernel
    p3 = layers.Conv2D(64, (7, 7), activation='relu', padding='same')(x)
    p3 = layers.MaxPooling2D((2, 2))(p3)

    # Concatenate multi-scale features
    x = layers.Concatenate()([p1, p2, p3])

    # Convolutional layers after multi-scale feature fusion
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Additional feature extraction layers
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Flatten and fully connected layers for classification
    x = layers.Flatten()(x)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    # Output layer with softmax for multi-class classification
    outputs = layers.Dense(n_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model

# Create and compile the model
model = create_oral_cancer_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
)

# Evaluate on test data
test_loss, test_acc = model.evaluate(test_ds)
print(f"Test accuracy: {test_acc}")

# Plotting Training and Validation Accuracy and Loss
def plot_history(history):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Training and Validation Accuracy')

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Training and Validation Loss')

    plt.show()

plot_history(history)

# Confusion Matrix and Classification Report
def plot_confusion_matrix(cm, class_names):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Generate predictions and calculate confusion matrix
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(model.predict(test_ds), axis=1)

cm = confusion_matrix(y_true, y_pred)
plot_confusion_matrix(cm, class_names)

# ROC Curve and AUC (for each class in a multi-class setting)
from sklearn.preprocessing import label_binarize

y_true_binarized = label_binarize(y_true, classes=[i for i in range(len(class_names))])
y_pred_prob = model.predict(test_ds)

plt.figure(figsize=(10, 8))
for i in range(len(class_names)):
    fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Each Class')
plt.legend(loc='lower right')
plt.show()

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Define a function to split the dataset into training, validation, and testing
def get_dataset_partitions_tf(ds, train_split=0.8, val_split=0.1, test_split=0.1, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split + val_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    val_size = int(val_split * ds_size)

    train_ds = ds.take(train_size)
    val_ds = ds.skip(train_size).take(val_size)
    test_ds = ds.skip(train_size).skip(val_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Validation set size: {len(val_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune all the 3 datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    val_ds = val_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, val_ds, test_ds

train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset)

# Check if validation dataset is empty
if len(val_ds) == 0:
    print("Warning: Validation dataset is empty. Adjusting dataset split ratios.")
    # Adjust splits to ensure validation data has samples
    train_ds, val_ds, test_ds = get_dataset_partitions_tf(dataset, train_split=0.7, val_split=0.15, test_split=0.15)

# Define data preprocessing and augmentation pipelines
resize_and_rescale = tf.keras.Sequential([
    layers.experimental.preprocessing.Resizing(IMAGE_SIZE, IMAGE_SIZE),
    layers.experimental.preprocessing.Rescaling(1./255),
])

# Model inspired by CST-YOLO, customized for classification
def create_oral_cancer_model(input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS), n_classes=len(class_names)):
    inputs = layers.Input(shape=input_shape)

    # Data preprocessing
    x = resize_and_rescale(inputs)

    # Backbone: Initial Convolutional Layers
    x = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Multi-scale feature extraction
    # Path 1
    p1 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    p1 = layers.MaxPooling2D((2, 2))(p1)

    # Path 2 with a larger kernel
    p2 = layers.Conv2D(64, (5, 5), activation='relu', padding='same')(x)
    p2 = layers.MaxPooling2D((2, 2))(p2)

    # Path 3 with a smaller kernel
    p3 = layers.Conv2D(64, (7, 7), activation='relu', padding='same')(x)
    p3 = layers.MaxPooling2D((2, 2))(p3)

    # Concatenate multi-scale features
    x = layers.Concatenate()([p1, p2, p3])

    # Convolutional layers after multi-scale feature fusion
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Additional feature extraction layers
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Flatten and fully connected layers for classification
    x = layers.Flatten()(x)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    # Output layer with softmax for multi-class classification
    outputs = layers.Dense(n_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model

# Create and compile the model
model = create_oral_cancer_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Model summary
model.summary()

# Train the model
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
)

# Evaluate on test data
test_loss, test_acc = model.evaluate(test_ds)
print(f"Test accuracy: {test_acc}")

# Plot Training and Validation Accuracy and Loss
def plot_history(history):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Training and Validation Accuracy')

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Training and Validation Loss')

    plt.show()

plot_history(history)

# Confusion Matrix and Classification Report
def plot_confusion_matrix(cm, class_names):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Generate predictions and calculate confusion matrix
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(hybrid_model.predict(test_ds), axis=1)

cm = confusion_matrix(y_true, y_pred)
plot_confusion_matrix(cm, class_names)

# ROC Curve and AUC (for each class in a multi-class setting)
from sklearn.preprocessing import label_binarize

y_true_binarized = label_binarize(y_true, classes=[i for i in range(N_CLASSES)])
y_pred_prob = hybrid_model.predict(test_ds)

plt.figure(figsize=(10, 8))
for i in range(N_CLASSES):
    fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Each Class')
plt.legend(loc='lower right')
plt.show()

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3

# Load the dataset
dataset_path = "/content/drive/My Drive/oral1/OralCancer1"

class_names = dataset.class_names

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# Define data preprocessing and augmentation pipelines
resize_and_rescale = tf.keras.Sequential([
    layers.experimental.preprocessing.Resizing(IMAGE_SIZE, IMAGE_SIZE),
    layers.experimental.preprocessing.Rescaling(1./255),
])

# Model inspired by CST-YOLO, customized for classification
def create_oral_cancer_model(input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS), n_classes=len(class_names)):
    inputs = layers.Input(shape=input_shape)

    # Data preprocessing
    x = resize_and_rescale(inputs)

    # Backbone: Initial Convolutional Layers
    x = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Multi-scale feature extraction
    # Path 1
    p1 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    p1 = layers.MaxPooling2D((2, 2))(p1)

    # Path 2 with a larger kernel
    p2 = layers.Conv2D(64, (5, 5), activation='relu', padding='same')(x)
    p2 = layers.MaxPooling2D((2, 2))(p2)

    # Path 3 with a smaller kernel
    p3 = layers.Conv2D(64, (7, 7), activation='relu', padding='same')(x)
    p3 = layers.MaxPooling2D((2, 2))(p3)

    # Concatenate multi-scale features
    x = layers.Concatenate()([p1, p2, p3])

    # Convolutional layers after multi-scale feature fusion
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Additional feature extraction layers
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Flatten and fully connected layers for classification
    x = layers.Flatten()(x)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    # Output layer with softmax for multi-class classification
    outputs = layers.Dense(n_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model

# Create and compile the model
model = create_oral_cancer_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Model summary
model.summary()

# Train the model with test set as validation data
history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
)

# Evaluate on test data
test_loss, test_acc = model.evaluate(test_ds)
print(f"Test accuracy: {test_acc}")

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
import numpy as np
import itertools

# Plot Training and Validation Accuracy and Loss
def plot_training_history(history):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Training and Validation Accuracy')

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Training and Validation Loss')

    plt.show()

# Call the function to plot accuracy and loss
plot_training_history(history)

# Confusion Matrix and Classification Report
def plot_confusion_matrix(cm, class_names):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Generate predictions and calculate confusion matrix
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(model.predict(test_ds), axis=1)

# Compute confusion matrix
cm = confusion_matrix(y_true, y_pred)
plot_confusion_matrix(cm, class_names)

# ROC Curve and AUC (for each class in a multi-class setting)
from sklearn.preprocessing import label_binarize

y_true_binarized = label_binarize(y_true, classes=[i for i in range(len(class_names))])
y_pred_prob = model.predict(test_ds)

plt.figure(figsize=(10, 8))
for i in range(len(class_names)):
    fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Each Class')
plt.legend(loc='lower right')
plt.show()

from sklearn.metrics import roc_curve, auc

# Check if binary classification
if len(class_names) == 2:
    # Only one class output, so use binary labels
    y_true_binarized = (y_true == 1).astype(int)  # Adjust if your positive class is labeled differently
    y_pred_prob = model.predict(test_ds)[:, 1]    # Use the probability of the positive class

    # Calculate ROC curve and AUC
    fpr, tpr, _ = roc_curve(y_true_binarized, y_pred_prob)
    roc_auc = auc(fpr, tpr)

    # Plot ROC curve
    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='blue', label=f'ROC curve (AUC = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve for Binary Classification')
    plt.legend(loc='lower right')
    plt.show()
else:
    # Multi-class ROC Curve (previous code for multi-class)
    y_true_binarized = label_binarize(y_true, classes=[i for i in range(len(class_names))])
    y_pred_prob = model.predict(test_ds)

    plt.figure(figsize=(10, 8))
    for i in range(len(class_names)):
        fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

    plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve for Each Class')
    plt.legend(loc='lower right')
    plt.show()

from sklearn.metrics import classification_report, confusion_matrix

# Generate predictions and true labels for the test set
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(model.predict(test_ds), axis=1)

# Classification Report
print("Classification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)

# Plot Confusion Matrix
def plot_confusion_matrix(cm, class_names):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Plot the confusion matrix
plot_confusion_matrix(cm, class_names)

import matplotlib.pyplot as plt

# Function to display predictions on test images
def show_test_predictions(model, test_ds, class_names, num_images=5):
    plt.figure(figsize=(15, 15))
    for images, labels in test_ds.take(1):  # Take one batch from the test set
        predictions = model.predict(images)
        pred_labels = np.argmax(predictions, axis=1)
        for i in range(num_images):
            ax = plt.subplot(1, num_images, i + 1)
            plt.imshow(images[i].numpy().astype("uint8"))
            true_label = class_names[labels[i]]
            predicted_label = class_names[pred_labels[i]]
            plt.title(f"True: {true_label}\nPred: {predicted_label}")
            plt.axis("off")

# Show some test predictions
show_test_predictions(model, test_ds, class_names, num_images=9)

import matplotlib.pyplot as plt

# Function to display predictions on test images in a 3x3 grid
def show_test_predictions(model, test_ds, class_names, num_images=9):
    plt.figure(figsize=(15, 15))
    for images, labels in test_ds.take(1):  # Take one batch from the test set
        predictions = model.predict(images)
        pred_labels = np.argmax(predictions, axis=1)
        for i in range(num_images):
            ax = plt.subplot(3, 3, i + 1)  # Arrange in a 3x3 grid
            plt.imshow(images[i].numpy().astype("uint8"))
            true_label = class_names[labels[i]]
            predicted_label = class_names[pred_labels[i]]
            plt.title(f"True: {true_label}\nPred: {predicted_label}")
            plt.axis("off")
    plt.tight_layout()
    plt.show()

# Show some test predictions in a 3x3 grid
show_test_predictions(model, test_ds, class_names, num_images=9)

# Imports
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 100
CHANNELS = 3

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# Define data preprocessing and augmentation pipelines
resize_and_rescale = tf.keras.Sequential([
    layers.experimental.preprocessing.Resizing(IMAGE_SIZE, IMAGE_SIZE),
    layers.experimental.preprocessing.Rescaling(1./255),
])

# Model inspired by CST-YOLO, customized for classification
def create_oral_cancer_model(input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS), n_classes=len(class_names)):
    inputs = layers.Input(shape=input_shape)

    # Data preprocessing
    x = resize_and_rescale(inputs)

    # Backbone: Initial Convolutional Layers
    x = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Multi-scale feature extraction
    # Path 1
    p1 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    p1 = layers.MaxPooling2D((2, 2))(p1)

    # Path 2 with a larger kernel
    p2 = layers.Conv2D(64, (5, 5), activation='relu', padding='same')(x)
    p2 = layers.MaxPooling2D((2, 2))(p2)

    # Path 3 with a smaller kernel
    p3 = layers.Conv2D(64, (7, 7), activation='relu', padding='same')(x)
    p3 = layers.MaxPooling2D((2, 2))(p3)

    # Concatenate multi-scale features
    x = layers.Concatenate()([p1, p2, p3])

    # Convolutional layers after multi-scale feature fusion
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Additional feature extraction layers
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    # Flatten and fully connected layers for classification
    x = layers.Flatten()(x)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    # Output layer with softmax for multi-class classification
    outputs = layers.Dense(n_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model

# Create and compile the model
model = create_oral_cancer_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Model summary
model.summary()

# Train the model with test set as validation data
history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
)

# Evaluate on test data
test_loss, test_acc = model.evaluate(test_ds)
print(f"Test accuracy: {test_acc}")

from tensorflow.keras.applications import VGG16
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping

# Define VGG16 model
def create_vgg16_model(input_shape, n_classes):
    base_model = VGG16(weights='imagenet', include_top=False, input_shape=input_shape)
    base_model.trainable = False  # Freeze base model layers

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(n_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train the VGG16 model
vgg16_model = create_vgg16_model((IMAGE_SIZE, IMAGE_SIZE, CHANNELS), len(class_names))
history_vgg16 = vgg16_model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS,
                                callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)])

# Evaluate the model on the test set
test_loss_vgg16, test_acc_vgg16 = vgg16_model.evaluate(test_ds)
print(f"VGG16 Test accuracy: {test_acc_vgg16}")

import tensorflow as tf
from tensorflow.keras import models, layers

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 100
CHANNELS = 3

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

from tensorflow.keras.applications import VGG16
from tensorflow.keras.callbacks import EarlyStopping

# Define VGG16 model
def create_vgg16_model(input_shape, n_classes):
    base_model = VGG16(weights='imagenet', include_top=False, input_shape=input_shape)
    base_model.trainable = False  # Freeze base model layers

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(n_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train the VGG16 model
vgg16_model = create_vgg16_model((IMAGE_SIZE, IMAGE_SIZE, CHANNELS), len(class_names))
history_vgg16 = vgg16_model.fit(train_ds, validation_data=test_ds, epochs=EPOCHS,
                                callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)])

# Evaluate the model on the test set
test_loss_vgg16, test_acc_vgg16 = vgg16_model.evaluate(test_ds)
print(f"VGG16 Test accuracy: {test_acc_vgg16}")

from tensorflow.keras.applications import ResNet50
from tensorflow.keras import models, layers

# Set input shape based on image dimensions
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)

# Define ResNet50 model
def create_resnet50_model(input_shape, n_classes):
    base_model = ResNet50(weights='imagenet', include_top=False, input_shape=input_shape)
    base_model.trainable = False  # Freeze base model layers

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(n_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train the ResNet50 model
resnet50_model = create_resnet50_model(input_shape, len(class_names))
history_resnet50 = resnet50_model.fit(train_ds, validation_data=test_ds, epochs=EPOCHS,
                                      callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)])

# Evaluate the model on the test set
test_loss_resnet50, test_acc_resnet50 = resnet50_model.evaluate(test_ds)
print(f"ResNet50 Test accuracy: {test_acc_resnet50}")





# Imports
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import numpy as np
import itertools

# Parameters
BATCH_SIZE = 32
IMAGE_SIZE = 256
EPOCHS = 100
CHANNELS = 3
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# Define VGG16 model
def create_vgg16_model(input_shape, n_classes):
    base_model = VGG16(weights='imagenet', include_top=False, input_shape=input_shape)
    base_model.trainable = False  # Freeze base model layers

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(n_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train the VGG16 model
vgg16_model = create_vgg16_model(input_shape, len(class_names))
history_vgg16 = vgg16_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
    callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)]
)

# Evaluate the model on the test set
test_loss_vgg16, test_acc_vgg16 = vgg16_model.evaluate(test_ds)
print(f"VGG16 Test accuracy: {test_acc_vgg16}")

# Plot Training and Validation Accuracy and Loss
def plot_training_history(history):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Training and Validation Accuracy')

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Training and Validation Loss')

    plt.show()

# Plot training history
plot_training_history(history_vgg16)

# Generate predictions and true labels for the test set
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(vgg16_model.predict(test_ds), axis=1)
y_pred_prob = vgg16_model.predict(test_ds)

# Classification Report
print("Classification Report for VGG16:")
print(classification_report(y_true, y_pred, target_names=class_names))

# Plot Confusion Matrix
def plot_confusion_matrix(cm, class_names, model_name="VGG16"):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title(f'{model_name} - Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Compute and plot confusion matrix
cm = confusion_matrix(y_true, y_pred)
plot_confusion_matrix(cm, class_names, model_name="VGG16")

# Plot ROC Curve
def plot_roc_curve(y_true, y_pred_prob, class_names, model_name="VGG16"):
    y_true_binarized = label_binarize(y_true, classes=[i for i in range(len(class_names))])
    plt.figure(figsize=(10, 8))
    for i in range(len(class_names)):
        fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

    plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'{model_name} - ROC Curve for Each Class')
    plt.legend(loc='lower right')
    plt.show()

# Plot ROC curve
plot_roc_curve(y_true, y_pred_prob, class_names, model_name="VGG16")





import os
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt

# Define path to OralCancer dataset
dataset_path = "/content/drive/My Drive/oral/OralCancer/OralCancer"

# Verify the dataset is accessible
print("Contents of OralCancer directory:", os.listdir(dataset_path))

# Set constants
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3

# Load dataset using image_dataset_from_directory
dataset = tf.keras.utils.image_dataset_from_directory(
    dataset_path,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

# Get class names
class_names = dataset.class_names
print("Class Names:", class_names)

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# ✅ Reconfigured CNN Model Based on Image (Model b)
def create_oral_cancer_model(input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS), n_classes=len(class_names)):
    inputs = layers.Input(shape=input_shape)

    # Augmentation Layer (shown in image)
    x = layers.RandomFlip("horizontal")(inputs)
    x = layers.RandomRotation(0.25)(x)
    x = layers.RandomZoom(0.25)(x)
    x = layers.RandomContrast(0.25)(x)
    x = layers.Rescaling(1./255)(x)

    # Block 1
    x = layers.Conv2D(32, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    # Block 2
    x = layers.Conv2D(64, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    # Block 3
    x = layers.Conv2D(128, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    # Block 7-N (more depth)
    x = layers.Conv2D(256, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Flatten()(x)

    # Dense + Dropout layers for fine-tuning
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    # Final Softmax classifier
    outputs = layers.Dense(n_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model

# Create and compile the model
model = create_oral_cancer_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Show model summary
model.summary()

# Train the model with test set as validation data
history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
)

# Evaluate on test data
test_loss, test_acc = model.evaluate(test_ds)
print(f"Test accuracy: {test_acc}")

import os
import shutil
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from PIL import Image

# -------------------------------
# 1. Parameters and Paths
# -------------------------------
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 10
CHANNELS = 3

original_data_path = "/content/drive/My Drive/oral1/OralCancer1"
augmented_data_path = "/content/augmented_oral_cancer_dataset"

# -------------------------------
# 2. Augment and Save Images
# -------------------------------

# Remove old augmented directory if it exists
if os.path.exists(augmented_data_path):
    shutil.rmtree(augmented_data_path)
os.makedirs(augmented_data_path, exist_ok=True)

# Define augmentation
datagen = ImageDataGenerator(
    rotation_range=30,
    zoom_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    rescale=1./255
)

target_count_per_class = 500  # Generate up to this number per class

for class_label in os.listdir(original_data_path):
    class_dir = os.path.join(original_data_path, class_label)
    save_dir = os.path.join(augmented_data_path, class_label)
    os.makedirs(save_dir, exist_ok=True)

    images = [f for f in os.listdir(class_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

    total_generated = 0

    for image_name in images:
        image_path = os.path.join(class_dir, image_name)
        img = Image.open(image_path).convert('RGB').resize((IMAGE_SIZE, IMAGE_SIZE))
        x = tf.keras.utils.img_to_array(img)
        x = x.reshape((1,) + x.shape)

        # Save the original image
        img.save(os.path.join(save_dir, f"original_{image_name}"))
        total_generated += 1

        # Generate augmented images
        i = 0
        for batch in datagen.flow(x, batch_size=1, save_to_dir=save_dir, save_prefix='aug', save_format='jpeg'):
            i += 1
            total_generated += 1
            if total_generated >= target_count_per_class:
                break
        if total_generated >= target_count_per_class:
            break

print("✅ Augmentation complete.")

# -------------------------------
# 3. Load Augmented Dataset
# -------------------------------
dataset = tf.keras.utils.image_dataset_from_directory(
    augmented_data_path,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names
print("Class Names:", class_names)

# -------------------------------
# 4. Train-Test Split
# -------------------------------
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# -------------------------------
# 5. Model Definition
# -------------------------------
resize_and_rescale = tf.keras.Sequential([
    layers.Resizing(IMAGE_SIZE, IMAGE_SIZE),
    layers.Rescaling(1./255),
])

def create_oral_cancer_model(input_shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS), n_classes=len(class_names)):
    inputs = layers.Input(shape=input_shape)
    x = resize_and_rescale(inputs)

    x = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    p1 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    p1 = layers.MaxPooling2D((2, 2))(p1)

    p2 = layers.Conv2D(64, (5, 5), activation='relu', padding='same')(x)
    p2 = layers.MaxPooling2D((2, 2))(p2)

    p3 = layers.Conv2D(64, (7, 7), activation='relu', padding='same')(x)
    p3 = layers.MaxPooling2D((2, 2))(p3)

    x = layers.Concatenate()([p1, p2, p3])
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Flatten()(x)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    outputs = layers.Dense(n_classes, activation='softmax')(x)
    model = models.Model(inputs, outputs)
    return model

# -------------------------------
# 6. Train the Model
# -------------------------------
model = create_oral_cancer_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
)

# Evaluate
test_loss, test_acc = model.evaluate(test_ds)
print(f"Test Accuracy: {test_acc}")

import numpy as np
import itertools
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt

# Get true labels and predictions from test dataset
y_true = []
y_pred = []
y_prob = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))
    y_prob.extend(preds)

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_prob = np.array(y_prob)

class_labels = class_names  # ['CANCER', 'NON CANCER']

# -------------------------------
# 1. Confusion Matrix
# -------------------------------
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_labels, yticklabels=class_labels)
plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

# -------------------------------
# 2. Classification Report
# -------------------------------
print("Classification Report:\n")
print(classification_report(y_true, y_pred, target_names=class_labels))

# -------------------------------
# 3. Train vs Validation Accuracy/Loss
# -------------------------------
plt.figure(figsize=(12, 5))

# Accuracy plot
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy', marker='o')
plt.plot(history.history['val_accuracy'], label='Val Accuracy', marker='x')
plt.title('Training vs Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss', marker='o')
plt.plot(history.history['val_loss'], label='Val Loss', marker='x')
plt.title('Training vs Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

# -------------------------------
# 4. ROC Curve
# -------------------------------
# Handle binary classification
fpr, tpr, _ = roc_curve(y_true, y_prob[:, 1])
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f"ROC curve (AUC = {roc_auc:.2f})")
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.title("Receiver Operating Characteristic (ROC)")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend(loc="lower right")
plt.grid()
plt.show()

from tensorflow.keras.utils import plot_model

# Save model diagram with shapes and layer names
plot_model(model, to_file='model_keras_plot.png', show_shapes=True, show_layer_names=True)

!pip install visualkeras
import visualkeras

visualkeras.layered_view(model, to_file='model_visualkeras.png', legend=True, max_xy=500)

