# -*- coding: utf-8 -*-
"""oral_finial_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxzWTMH_FkpA09gT95g4U2l7RhyRipdJ
"""

# Imports
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import numpy as np
import itertools

# Parameters
BATCH_SIZE = 32
IMAGE_SIZE = 256
EPOCHS = 30
CHANNELS = 3
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# Define VGG16 model
def create_vgg16_model(input_shape, n_classes):
    base_model = VGG16(weights='imagenet', include_top=False, input_shape=input_shape)
    base_model.trainable = False  # Freeze base model layers

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(n_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train the VGG16 model
vgg16_model = create_vgg16_model(input_shape, len(class_names))
history_vgg16 = vgg16_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
    callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)]
)

# Evaluate the model on the test set
test_loss_vgg16, test_acc_vgg16 = vgg16_model.evaluate(test_ds)
print(f"VGG16 Test accuracy: {test_acc_vgg16}")

# Plot Training and Validation Accuracy and Loss
def plot_training_history(history):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Training and Validation Accuracy')

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Training and Validation Loss')

    plt.show()

# Plot training history
plot_training_history(history_vgg16)

# Generate predictions and true labels for the test set
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(vgg16_model.predict(test_ds), axis=1)
y_pred_prob = vgg16_model.predict(test_ds)

# Classification Report
print("Classification Report for VGG16:")
print(classification_report(y_true, y_pred, target_names=class_names))

# Plot Confusion Matrix
def plot_confusion_matrix(cm, class_names, model_name="VGG16"):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title(f'{model_name} - Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Compute and plot confusion matrix
cm = confusion_matrix(y_true, y_pred)
plot_confusion_matrix(cm, class_names, model_name="VGG16")

# Plot ROC Curve
def plot_roc_curve(y_true, y_pred_prob, class_names, model_name="VGG16"):
    y_true_binarized = label_binarize(y_true, classes=[i for i in range(len(class_names))])
    plt.figure(figsize=(10, 8))
    for i in range(len(class_names)):
        fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

    plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'{model_name} - ROC Curve for Each Class')
    plt.legend(loc='lower right')
    plt.show()

# Plot ROC curve
plot_roc_curve(y_true, y_pred_prob, class_names, model_name="VGG16")

# Imports
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt
import numpy as np
import itertools

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# Define the VGG16 model with custom dense layers for your classification task
def create_vgg16_model(input_shape, n_classes):
    base_model = VGG16(weights='imagenet', include_top=False, input_shape=input_shape)
    base_model.trainable = False  # Freeze base model layers

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(n_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train the VGG16 model
vgg16_model = create_vgg16_model(input_shape, len(class_names))
history_vgg16 = vgg16_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
    callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)]
)

# Evaluate the model on the test set
test_loss_vgg16, test_acc_vgg16 = vgg16_model.evaluate(test_ds)
print(f"VGG16 Test accuracy: {test_acc_vgg16}")

# Plot Training and Validation Accuracy and Loss
def plot_training_history(history):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Training and Validation Accuracy')

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Training and Validation Loss')

    plt.show()

# Plot training history
plot_training_history(history_vgg16)

# Generate predictions and true labels for the test set
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(vgg16_model.predict(test_ds), axis=1)
y_pred_prob = vgg16_model.predict(test_ds)

# Classification Report
print("Classification Report for VGG16:")
print(classification_report(y_true, y_pred, target_names=class_names))

# Plot Confusion Matrix
def plot_confusion_matrix(cm, class_names, model_name="VGG16"):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title(f'{model_name} - Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Compute and plot confusion matrix
cm = confusion_matrix(y_true, y_pred)
plot_confusion_matrix(cm, class_names, model_name="VGG16")

# Plot ROC Curve
def plot_roc_curve(y_true, y_pred_prob, class_names, model_name="VGG16"):
    y_true_binarized = label_binarize(y_true, classes=[i for i in range(len(class_names))])
    plt.figure(figsize=(10, 8))
    for i in range(len(class_names)):
        fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

    plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'{model_name} - ROC Curve for Each Class')
    plt.legend(loc='lower right')
    plt.show()

# Plot ROC curve
plot_roc_curve(y_true, y_pred_prob, class_names, model_name="VGG16")

# Imports
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt
import numpy as np
import itertools

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# Define the InceptionV3 model with custom dense layers for your classification task
def create_inceptionv3_model(input_shape, n_classes):
    base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=input_shape)
    base_model.trainable = False  # Freeze base model layers

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(n_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train the InceptionV3 model
inceptionv3_model = create_inceptionv3_model(input_shape, len(class_names))
history_inceptionv3 = inceptionv3_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
    callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)]
)

# Evaluate the model on the test set
test_loss_inceptionv3, test_acc_inceptionv3 = inceptionv3_model.evaluate(test_ds)
print(f"InceptionV3 Test accuracy: {test_acc_inceptionv3}")

# Plot Training and Validation Accuracy and Loss
def plot_training_history(history):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Training and Validation Accuracy')

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Training and Validation Loss')

    plt.show()

# Plot training history
plot_training_history(history_inceptionv3)

# Generate predictions and true labels for the test set
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(inceptionv3_model.predict(test_ds), axis=1)
y_pred_prob = inceptionv3_model.predict(test_ds)

# Classification Report
print("Classification Report for InceptionV3:")
print(classification_report(y_true, y_pred, target_names=class_names))

# Plot Confusion Matrix
def plot_confusion_matrix(cm, class_names, model_name="InceptionV3"):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title(f'{model_name} - Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Compute and plot confusion matrix
cm = confusion_matrix(y_true, y_pred)
plot_confusion_matrix(cm, class_names, model_name="InceptionV3")

# Plot ROC Curve
def plot_roc_curve(y_true, y_pred_prob, class_names, model_name="InceptionV3"):
    try:
        # Check if binary or multi-class classification
        if len(class_names) == 2:
            # Binary classification ROC curve
            y_true_binarized = np.where(np.array(y_true) == 1, 1, 0)
            fpr, tpr, _ = roc_curve(y_true_binarized, y_pred_prob[:, 1])
            roc_auc = auc(fpr, tpr)

            plt.figure(figsize=(8, 8))
            plt.plot(fpr, tpr, color='darkorange', label=f'ROC curve (area = {roc_auc:.2f})')
            plt.plot([0, 1], [0, 1], 'k--')
            plt.xlim([0.0, 1.0])
            plt.ylim([0.0, 1.05])
            plt.xlabel('False Positive Rate')
            plt.ylabel('True Positive Rate')
            plt.title(f'{model_name} - ROC Curve')
            plt.legend(loc="lower right")
            plt.show()
        else:
            # Multi-class ROC curve
            y_true_binarized = label_binarize(y_true, classes=[i for i in range(len(class_names))])

            plt.figure(figsize=(10, 8))
            for i in range(len(class_names)):
                fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
                roc_auc = auc(fpr, tpr)
                plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

            plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
            plt.xlabel('False Positive Rate')
            plt.ylabel('True Positive Rate')
            plt.title(f'{model_name} - ROC Curve for Each Class')
            plt.legend(loc='lower right')
            plt.show()
    except IndexError as e:
        print("IndexError:", e)
        print("This error often occurs if y_pred_prob doesn't match the number of classes.")
    except Exception as e:
        print("Error:", e)
        print("Please check that y_true and y_pred_prob are correctly shaped.")

# Plot ROC Curve
plot_roc_curve(y_true, y_pred_prob, class_names, model_name="InceptionV3")

# Imports
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt
import numpy as np
import itertools

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# Define the MobileNetV2 model with custom dense layers for your classification task
def create_mobilenetv2_model(input_shape, n_classes):
    base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=input_shape)
    base_model.trainable = False  # Freeze base model layers

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(n_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train the MobileNetV2 model
mobilenetv2_model = create_mobilenetv2_model(input_shape, len(class_names))
history_mobilenetv2 = mobilenetv2_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
    callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)]
)

# Evaluate the model on the test set
test_loss_mobilenetv2, test_acc_mobilenetv2 = mobilenetv2_model.evaluate(test_ds)
print(f"MobileNetV2 Test accuracy: {test_acc_mobilenetv2}")

# Plot Training and Validation Accuracy and Loss
def plot_training_history(history):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Training and Validation Accuracy')

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Training and Validation Loss')

    plt.show()

# Plot training history
plot_training_history(history_mobilenetv2)

# Generate predictions and true labels for the test set
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(mobilenetv2_model.predict(test_ds), axis=1)
y_pred_prob = mobilenetv2_model.predict(test_ds)

# Classification Report
print("Classification Report for MobileNetV2:")
print(classification_report(y_true, y_pred, target_names=class_names))

# Plot Confusion Matrix
def plot_confusion_matrix(cm, class_names, model_name="MobileNetV2"):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title(f'{model_name} - Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Compute and plot confusion matrix
cm = confusion_matrix(y_true, y_pred)
plot_confusion_matrix(cm, class_names, model_name="MobileNetV2")

# Plot ROC Curve
def plot_roc_curve(y_true, y_pred_prob, class_names, model_name="MobileNetV2"):
    try:
        # Check if binary or multi-class classification
        if len(class_names) == 2:
            # Binary classification ROC curve
            y_true_binarized = np.where(np.array(y_true) == 1, 1, 0)
            fpr, tpr, _ = roc_curve(y_true_binarized, y_pred_prob[:, 1])
            roc_auc = auc(fpr, tpr)

            plt.figure(figsize=(8, 8))
            plt.plot(fpr, tpr, color='darkorange', label=f'ROC curve (area = {roc_auc:.2f})')
            plt.plot([0, 1], [0, 1], 'k--')
            plt.xlim([0.0, 1.0])
            plt.ylim([0.0, 1.05])
            plt.xlabel('False Positive Rate')
            plt.ylabel('True Positive Rate')
            plt.title(f'{model_name} - ROC Curve')
            plt.legend(loc="lower right")
            plt.show()
        else:
            # Multi-class ROC curve
            y_true_binarized = label_binarize(y_true, classes=[i for i in range(len(class_names))])

            plt.figure(figsize=(10, 8))
            for i in range(len(class_names)):
                fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
                roc_auc = auc(fpr, tpr)
                plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

            plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
            plt.xlabel('False Positive Rate')
            plt.ylabel('True Positive Rate')
            plt.title(f'{model_name} - ROC Curve for Each Class')
            plt.legend(loc='lower right')
            plt.show()
    except IndexError as e:
        print("IndexError:", e)
        print("This error often occurs if y_pred_prob doesn't match the number of classes.")
    except Exception as e:
        print("Error:", e)
        print("Please check that y_true and y_pred_prob are correctly shaped.")

# Plot ROC Curve
plot_roc_curve(y_true, y_pred_prob, class_names, model_name="MobileNetV2")

# Imports
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt
import numpy as np
import itertools

# Parameters
BATCH_SIZE = 62
IMAGE_SIZE = 256
EPOCHS = 70
CHANNELS = 3
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)

# Load the dataset
dataset = tf.keras.preprocessing.image_dataset_from_directory(
   r'C:\Users\VIT-AP\Desktop\Irfan\archive (2)\OralCancer',
    seed=123,
    shuffle=True,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = dataset.class_names

# Split dataset into training and testing only
def get_train_test_partition(ds, train_split=0.8, test_split=0.2, shuffle=True, shuffle_size=10000):
    assert (train_split + test_split) == 1
    ds_size = len(ds)
    if shuffle:
        ds = ds.shuffle(shuffle_size, seed=12)
    train_size = int(train_split * ds_size)
    train_ds = ds.take(train_size)
    test_ds = ds.skip(train_size)

    # Print dataset sizes for verification
    print(f"Total dataset size: {ds_size}")
    print(f"Training set size: {len(train_ds)}")
    print(f"Test set size: {len(test_ds)}")

    # Autotune both datasets
    train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
    test_ds = test_ds.cache().prefetch(buffer_size=tf.data.AUTOTUNE)

    return train_ds, test_ds

train_ds, test_ds = get_train_test_partition(dataset)

# Define the DenseNet121 model with custom dense layers for your classification task
def create_densenet121_model(input_shape, n_classes):
    base_model = DenseNet121(weights='imagenet', include_top=False, input_shape=input_shape)
    base_model.trainable = False  # Freeze base model layers

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(n_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train the DenseNet121 model
densenet121_model = create_densenet121_model(input_shape, len(class_names))
history_densenet121 = densenet121_model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS,
    callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)]
)

# Evaluate the model on the test set
test_loss_densenet121, test_acc_densenet121 = densenet121_model.evaluate(test_ds)
print(f"DenseNet121 Test accuracy: {test_acc_densenet121}")

# Plot Training and Validation Accuracy and Loss
def plot_training_history(history):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Training and Validation Accuracy')

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Training and Validation Loss')

    plt.show()

# Plot training history
plot_training_history(history_densenet121)

# Generate predictions and true labels for the test set
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred = np.argmax(densenet121_model.predict(test_ds), axis=1)
y_pred_prob = densenet121_model.predict(test_ds)

# Classification Report
print("Classification Report for DenseNet121:")
print(classification_report(y_true, y_pred, target_names=class_names))

# Plot Confusion Matrix
def plot_confusion_matrix(cm, class_names, model_name="DenseNet121"):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title(f'{model_name} - Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    fmt = 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Compute and plot confusion matrix
cm = confusion_matrix(y_true, y_pred)
plot_confusion_matrix(cm, class_names, model_name="DenseNet121")

# Plot ROC Curve
def plot_roc_curve(y_true, y_pred_prob, class_names, model_name="DenseNet121"):
    try:
        # Check if binary or multi-class classification
        if len(class_names) == 2:
            # Binary classification ROC curve
            y_true_binarized = np.where(np.array(y_true) == 1, 1, 0)
            fpr, tpr, _ = roc_curve(y_true_binarized, y_pred_prob[:, 1])
            roc_auc = auc(fpr, tpr)

            plt.figure(figsize=(8, 8))
            plt.plot(fpr, tpr, color='darkorange', label=f'ROC curve (area = {roc_auc:.2f})')
            plt.plot([0, 1], [0, 1], 'k--')
            plt.xlim([0.0, 1.0])
            plt.ylim([0.0, 1.05])
            plt.xlabel('False Positive Rate')
            plt.ylabel('True Positive Rate')
            plt.title(f'{model_name} - ROC Curve')
            plt.legend(loc="lower right")
            plt.show()
        else:
            # Multi-class ROC curve
            y_true_binarized = label_binarize(y_true, classes=[i for i in range(len(class_names))])

            plt.figure(figsize=(10, 8))
            for i in range(len(class_names)):
                fpr, tpr, _ = roc_curve(y_true_binarized[:, i], y_pred_prob[:, i])
                roc_auc = auc(fpr, tpr)
                plt.plot(fpr, tpr, label=f'Class {class_names[i]} (AUC = {roc_auc:.2f})')

            plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
            plt.xlabel('False Positive Rate')
            plt.ylabel('True Positive Rate')
            plt.title(f'{model_name} - ROC Curve for Each Class')
            plt.legend(loc='lower right')
            plt.show()
    except IndexError as e:
        print("IndexError:", e)
        print("This error often occurs if y_pred_prob doesn't match the number of classes.")
    except Exception as e:
        print("Error:", e)
        print("Please check that y_true and y_pred_prob are correctly shaped.")

# Plot ROC Curve
plot_roc_curve(y_true, y_pred_prob, class_names, model_name="DenseNet121")

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.metrics import confusion_matrix

# Example confusion matrix values
y_true = ['cancer'] * 42 + ['non-cancer'] * 20
y_pred = ['cancer'] * 41 + ['non-cancer'] + ['cancer'] + ['non-cancer'] * 19

# Compute confusion matrix
cm = confusion_matrix(y_true, y_pred, labels=["cancer", "non-cancer"])

# Plot
plt.figure(figsize=(10, 8))
sns.set(font_scale=1.8)  # Increase overall font scale
ax = sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True,
                 xticklabels=["cancer", "non-cancer"],
                 yticklabels=["cancer", "non-cancer"],
                 annot_kws={"size": 24})  # Make value text larger

plt.title('MobileNetV2 - Confusion Matrix', fontsize=22)
plt.xlabel('Predicted label', fontsize=20)
plt.ylabel('True label', fontsize=20)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Updated confusion matrix values
cm = np.array([[129, 0],
               [0, 119]])

labels = ['cancer', 'non-cancer']

# Plot
plt.figure(figsize=(10, 8))
sns.set(font_scale=1.8)  # Controls general font size
ax = sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True,
                 xticklabels=labels, yticklabels=labels,
                 annot_kws={"size": 24})  # Enlarges numbers in cells

plt.title('Confusion Matrix', fontsize=22)
plt.xlabel('Predicted Label', fontsize=20)
plt.ylabel('True Label', fontsize=20)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Confusion matrix values
cm = np.array([[42, 0],
               [1, 19]])

labels = ['cancer', 'non-cancer']

# Plot with larger size and font
plt.figure(figsize=(10, 8))
sns.set(font_scale=1.8)  # Enlarges axis and tick label fonts
ax = sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True,
                 xticklabels=labels, yticklabels=labels,
                 annot_kws={"size": 24})  # Enlarges numbers in boxes

# Titles and labels
plt.title('Confusion Matrix', fontsize=22)
plt.xlabel('Predicted label', fontsize=20)
plt.ylabel('True label', fontsize=20)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# VGG16 Confusion Matrix Values
cm = np.array([[41, 1],
               [1, 19]])

labels = ['cancer', 'non-cancer']

# Create the heatmap
plt.figure(figsize=(10, 8))  # Increase overall figure size
sns.set(font_scale=1.8)  # Increase font scale for axes
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True,
            xticklabels=labels, yticklabels=labels,
            annot_kws={"size": 24})  # Make text inside boxes larger

# Add labels and title
plt.title('VGG16 - Confusion Matrix', fontsize=22)
plt.xlabel('Predicted label', fontsize=20)
plt.ylabel('True label', fontsize=20)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Confusion matrix values for InceptionV3
cm = np.array([[42, 0],
               [6, 14]])

labels = ['cancer', 'non-cancer']

# Plot with enhanced visual clarity
plt.figure(figsize=(10, 8))
sns.set(font_scale=1.8)  # Increase all font sizes
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True,
            xticklabels=labels, yticklabels=labels,
            annot_kws={"size": 24})  # Big numbers in cells

# Add labels and title
plt.title('InceptionV3 - Confusion Matrix', fontsize=22)
plt.xlabel('Predicted label', fontsize=20)
plt.ylabel('True label', fontsize=20)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Confusion matrix values for DenseNet121
cm = np.array([[42, 0],
               [2, 18]])

labels = ['cancer', 'non-cancer']

# Plot
plt.figure(figsize=(10, 8))
sns.set(font_scale=1.8)  # Increase font size for axis labels
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True,
            xticklabels=labels, yticklabels=labels,
            annot_kws={"size": 24})  # Larger font inside cells

# Titles and labels
plt.title('DenseNet121 - Confusion Matrix', fontsize=22)
plt.xlabel('Predicted label', fontsize=20)
plt.ylabel('True label', fontsize=20)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)

plt.tight_layout()
plt.show()

